[hz] # float
update_status = 1.0
check_internet = 0.2
reset_signal = 5.0

[cmd] # string
check_internet_cmd = "ping -c 3 baidu.com; echo $?"

[timeout_s] # int
wifi_service = 10
ip_service = 1
touch_signal_effective = 10
camera_signal_effective = 1

[topic] # string
connector = "connector_state"
touch = "touch_state"
camera = "/camera/color/image_raw"
wifi = "wifi_status"
grpc = "ip_notify"

[service] # string
led = "led_state"
wifi = "connect_wifi"
ip = "ip_state"

[wifi] # string
ssid = "ssid"
password = "password"
provider = "provider"