[connector]                     # WiFi 连接
[connector.initialization]      # WiFi 连接:初始化
[connector.initialization.hz]   # float
update_status = 1.0                 # 更新连接状态数据
reset_signal = 5.0                  # 重置信号量（用于判断touch超时）

[connector.initialization.cmd]  # string
check_internet_cmd = "ping -c 3 mi.com; echo $?"

[connector.initialization.timeout_s]    # int
wait_for_service = 3                        # 等待 service 出现
wait_for_wifi_service_response = 20         # 等待 wifi service 响应
wait_for_camera_service_response = 10       # 等待 camera service 响应
touch_signal_effective = 120                # 触摸板有效期
same_wifi_connector_wait = 3                # 相同 wifi 连接等待时间（处理时间）
different_wifi_connector_wait = 10          # 不同 wifi 连接等待时间（处理时间）

[connector.initialization.topic] # string
connector = "connector_state"
touch = "touch_status"
camera = "image"
wifi = "wifi_status"
grpc = "ip_notify"
audio = "speech_play"
disconnect_app = "disconnect_app"

[connector.initialization.service] # string
connection = "connect"
audio = "speech_text_play"
led = "led_state"
wifi = "connect_wifi"
ip = "ip_state"
camera = "camera_service"

[connector.initialization.action] # string
audio = "speech_text_action"

[connector.initialization.image] # string
width = 2560
height = 1920
fps = 10
