[connector]                     # WiFi 连接
[connector.initialization]                  # WiFi 连接:初始化
[connector.initialization.hz] # float
update_status = 1.0
check_internet = 0.2
reset_signal = 5.0

[connector.initialization.cmd] # string
check_internet_cmd = "ping -c 3 mi.com; echo $?"

[connector.initialization.timeout_s] # int
wifi_service = 30
ip_service = 1
touch_signal_effective = 60
camera_signal_effective = 1
wifi_wait_time_same = 3
wifi_wait_time_different = 7

[connector.initialization.topic] # string
connector = "connector_state"
touch = "touch_status"
camera = "image"
wifi = "wifi_status"
grpc = "ip_notify"
audio = "speech_play"
disconnect_app = "disconnect_app"

[connector.initialization.service] # string
connection = "connect"
led = "led_state"
wifi = "connect_wifi"
ip = "ip_state"
camera = "camera_service"

[connector.initialization.action] # string
audio = "speech_text_action"

[connector.initialization.image] # string
width = 2560
height = 1920
fps = 10
