---
uint8 status 

uint8 ALGO_TASK_AB = 1
uint8 ALGO_TASK_MAPPING = 5
uint8 ALGO_TASK_LOCALIZATION = 7
uint8 ALGO_TASK_AUTO_DOCKING = 9
uint8 ALGO_TASK_UWB_TRACKING = 11
uint8 ALGO_TASK_VISION_TRACKING = 13
uint8 UNINITIALIZED = 100
uint8 IDLE = 101
uint8 STOPPINGTASK = 103
int32 code