
int32 COMMAND_RECOGNITION_ALL = 0
int32 COMMAND_RECOGNITION_SINGLE = 1

int32 command
string username
int32 id
int32 timeout #有效时间1～300，default = 60

---
int32 ENABLE_SUCCESS = 0
int32 ENABLE_FAIL = 5901
int32 result