
# client 
string LOWPOWER ="lowpower"
string BMS ="bms"
string CONNECTOR ="connector"
string VP ="vp"
string TRACKING = "tracking"
string SYSTEM = "system"

# target
uint8 HEAD_LED =1
uint8 TAIL_LED =2
uint8 MINI_LED =3


# mode
uint8 SYSTEM_PREDEFINED =0x01          #使用系统预定义的模式，此模式下，用户使用时只需从effect字段中
                                       #选择所需灯效。r_value、g_value、b_value字段无意义。
                                       #例如 target = 1 effect = 0xA1 代表头灯红常亮。
uint8 USER_DEFINED =0x02               #使用用户自定义的模式，此模式下，灯效由effect和r_value、g_value、
                                       #b_value字段联合决定。effect字段决定灯亮的方式，r_value、g_value、b_value
                                       #字段决定灯效的颜色。例如 target = 1，effect = 0x01， r_value =255 
                                       #g_value =0 b_value=0 代表头灯红灯亮。

# effect
#HEAD_LED和TAIL_LED的基础灯效（0x01 ～0x09），在 mode = USER_DEFINED 时配合r_value、g_value、b_value使用。
uint8 RGB_ON =0x01                     #常亮
uint8 BLINK =0x02                      #闪烁
uint8 BLINK_FAST =0x03                 #快速闪烁    
uint8 BREATH =0x04                     #呼吸
uint8 BREATH_FAST =0x05                #快速呼吸 
uint8 ONE_BY_ONE =0x06                 #逐个点亮
uint8 ONE_BY_ONE_FAST =0x07            #快速逐个点亮
uint8 BACK_AND_FORTH =0x08             #往返逐个点亮
uint8 TRAILING_RACE =0x09              #拖尾流跑马 


# HEAD_LED和TAIL_LED系统预定义的灯效（0xA0 ～0xB5），在mode = SYSTEM_PREDEFINED 时有效。
uint8 RGB_OFF =0xA0                    #常灭

uint8 RED_ON =0xA1                     #红灯常亮
uint8 RED_BLINK =0xA2                  #红灯闪烁
uint8 RED_BLINK_FAST =0xA3             #红灯快速闪烁
uint8 RED_BREATH =0xA4                 #红灯呼吸
uint8 RED_BREATH_FAST =0xA5            #红灯快速呼吸
uint8 RED_ONE_BY_ONE =0xA6             #红灯逐个点亮
uint8 RED_ONE_BY_ONE_FAST =0xA7        #红灯快速逐个点亮

uint8 BLUE_ON =0xA8                    #蓝灯常亮
uint8 BLUE_BLINK =0xA9                 #蓝灯闪烁
uint8 BLUE_BLINK_FAST =0xAA            #蓝灯快速闪烁
uint8 BLUE_BREATH =0xAB                #蓝灯呼吸
uint8 BLUE_BREATH_FAST =0xAC           #蓝灯快速呼吸
uint8 BLUE_ONE_BY_ONE =0xAD            #蓝灯逐个点亮
uint8 BLUE_ONE_BY_ONE_FAST =0xAE       #蓝灯快速逐个点亮

uint8 YELLOW_ON =0xAF                  #黄灯常亮
uint8 YELLOW_BLINK =0xB0               #黄灯闪烁
uint8 YELLOW_BLINK_FAST =0xB1          #黄灯快速闪烁
uint8 YELLOW_BREATH =0xB2              #黄灯呼吸
uint8 YELLOW_BREATH_FAST =0xB3         #黄灯快速呼吸
uint8 YELLOW_ONE_BY_ONE =0xB4          #黄灯逐个点亮
uint8 YELLOW_ONE_BY_ONE_FAST =0xB5     #黄灯快速逐个点亮

#MINI LED的基础灯效（0x30 ～0x31），在 mode = USER_DEFINED 时配合r_value、g_value、b_value使用。
uint8 CIRCULAR_BREATH = 0x30           #圆形缩放
uint8 CIRCULAR_RING = 0x31             #画圆环

# MINI LED系统预定义的灯效（0x32 ～0x36），在mode = SYSTEM_PREDEFINED 时有效。
uint8 MINI_OFF = 0x32                  #常灭
uint8 RECTANGLE_COLOR = 0x33           #方块变色(无须设定r,g,b取值)
uint8 CENTRE_COLOR = 0x34              #中间彩带(无须设定r,g,b取值)
uint8 THREE_CIRCULAR = 0x35            #三圆呼吸(无须设定r,g,b取值)
uint8 COLOR_ONE_BY_ONE = 0x36          #彩带逐个点亮(无须设定r,g,b取值)

# request
bool occupation                        # client是否占用target led，若为false,用户会释放优先级占用。该led会执行优先级队列中低优先级用户的请求。
string client                          # 使用模块，例如"bms";"vp";"connector" 具体见协议中常量定义
uint8 target                           # 用户希望使用的灯，可选择 HEAD_LED , TAIL_LED, MINI_LED
uint8 mode                             # 用户采用的模式（自定义USER_DEFINED/预置SYSTEM_PREDEFINED），取值见协议中常量定义
uint8 effect                           # 灯效，见协议中常量定义
uint8 r_value                          # 自定义模式下，红色通道的灰度值，取值范围0～255，其它模式下无意义。
uint8 g_value                          # 自定义模式下，绿色通道的灰度值，取值范围0～255，其它模式下无意义。
uint8 b_value                          # 自定义模式下，蓝色通道的灰度值，取值范围0～255，其它模式下无意义。


---
# response 
int32 SUCCEED =0                        # 当前请求参数合理，优先级最高，请求灯效执行成功
int32 TIMEOUT =1107                     # 当前请求led硬件响应超时
int32 TARGET_ERROR =1121                # 当前请求的target参数为空或者不在可选列表中
int32 PRIORITY_ERROR =1122              # 当前请求的client为空或者不在预设的优先级列表中
int32 MODE_ERROR = 1123                 # 当前请求的mode参数为空或者不在可选列表中
int32 EFFECT_ERROR =1124                # 当前请求的effect参数为空或者不在可选列表中
int32 LOW_PRIORITY = 1125               # 当前请求优先级较低，无法立即执行请求灯效

int32 code #执行结果