int32 DEFINITION = 0
int32 EXECUTION = 1

int32 APP = 0
int32 AUDIO = 1
int32 VIS = 2

# request
int32 cmd_type      # 定义动作/执行动作
int32 cmd_source 
int32 motion_id

---
# response
int32       motion_id    # 机器人运控姿态
bool        result       # 执行结果
int32       code         # module code