std_msgs/Header header

uint16 batt_volt
int16 batt_curr
uint8 batt_soc
int16 batt_temp
int16 power_adapter_temp
int16 wireless_charging_temp
uint8 batt_st
uint8 key_val
uint8 disable_charge
uint8 power_supply
uint8 buzze
uint8 status
int8  batt_health
int16 batt_loop_number
int8  powerboard_status

bool power_normal
bool power_wired_charging
bool power_finished_charging
bool power_motor_shutdown
bool power_soft_shutdown
bool power_wp_place
bool power_wp_charging
bool power_expower_supply
