int32 NO_GESTURE =0                                      #没有手势
int32 PULLING_HAND_OR_TWO_FINGERS_IN =1                  #手掌拉近
int32 PUSHING_HAND_OR_TWO_FINGERS_AWAY =2                #手掌推开
int32 SLIDING_HAND_OR_TWO_FINGERS_UP = 3                 #手向上抬
int32 SLIDING_HAND_OR_TWO_FINGERS_DOWN =4                #手向下压
int32 SLIDING_HAND_OR_TWO_FINGERS_LEFT =5                #手向左推
int32 SLIDING_HAND_OR_TWO_FINGERS_RIGHT =6               #手向右推
int32 STOP_SIGN =7                                       #停止手势 
int32 THUMB_UP =8                                        #大拇指朝上
int32 ZOOMING_IN_WITH_HAND_OR_TWO_FINGERS = 9            #张开手掌或手指
int32 ZOOMING_OUT_WITH_HAND_OR_TWO_FINGERS =10           #闭合手掌或手指
int32 THUMB_DOWN =11                                     #大拇指朝下


int32 id                                                 #手势识别结果id
