# 用于可视化编程项目包
string TYPE_TASK="task"                 # 任务
string TYPE_MODULE="module"             # 模块

string MODE_SINGLE="single"             # 单次
string MODE_CYCLE="cycle"               # 周期
string MODE_BASE="base"                 # 基础
string MODE_USER="user"                 # 用户

string OPERATE_ADD="add"                # [操作]添加
string OPERATE_REVISE="revise"          # [操作]修改
string OPERATE_DELETE="delete"          # [操作]删除
string OPERATE_SHUTDOWN="shutdown"      # [操作]终止
string OPERATE_SUSPEND="suspend"        # [操作]暂停
string OPERATE_RECOVER="recover"        # [操作]继续
string OPERATE_INQUIRY="inquiry"        # [操作]查询
string OPERATE_START="start"            # [操作]开始
string OPERATE_STOP="stop"              # [操作]停止

string STATE_NULL="null"                # [状态]空
string STATE_WAIT="wait"                # [状态]等待
string STATE_RUN="run"                  # [状态]执行
string STATE_SUSPEND="suspend"          # [状态]暂停
string STATE_SHUTDOWN="shutdown"        # [状态]终止

string STEP_PARSE="parse"               # [条件]解析
string STEP_REGISTER="register"         # [条件]注册

string type
string id
string describe
string style
string operate
string mode
string condition
string body
