#goal definition
geometry_msgs/PoseStamped[] poses
uint8 nav_type
uint8 NAVIGATION_TYPE_UNKNWON = 0
uint8 NAVIGATION_TYPE_START_AB = 1
uint8 NAVIGATION_TYPE_STOP_AB = 2
uint8 NAVIGATION_TYPE_START_FOLLOW = 3
uint8 NAVIGATION_TYPE_STOP_FOLLOW = 4
uint8 NAVIGATION_TYPE_START_MAPPING = 5
uint8 NAVIGATION_TYPE_STOP_MAPPING = 6
uint8 NAVIGATION_TYPE_START_LOCALIZATION = 7
uint8 NAVIGATION_TYPE_STOP_LOCALIZATION = 8
uint8 NAVIGATION_TYPE_START_AUTO_DOCKING = 9
uint8 NAVIGATION_TYPE_STOP_AUTO_DOCKING = 10

---
#result definition
uint8 result
uint8 NAVIGATION_RESULT_TYPE_SUCCESS = 0 
uint8 NAVIGATION_RESULT_TYPE_ACCEPT = 1
uint8 NAVIGATION_RESULT_TYPE_UNAVALIBLE =2
uint8 NAVIGATION_RESULT_TYPE_FAILED = 3
uint8 NAVIGATION_RESULT_TYPE_REJECT = 4
uint8 NAVIGATION_RESULT_TYPE_CANCEL = 5
---
#geometry_msgs/PoseStamped current_pose
#builtin_interfaces/Duration navigation_time
#builtin_interfaces/Duration estimated_time_remaining
#int16 number_of_recoveries
#float32 distance_remaining
#int16 number_of_poses_remaining