#goal definition
uint8 SEATADJUST_GOAL_TYPE_STOP = 0
uint8 SEATADJUST_GOAL_TYPE_START = 1
uint8 start
---
#result definition
uint8 result
uint8 SEATADJUST_RESULT_TYPE_SUCCESS = 0 
uint8 SEATADJUST_RESULT_TYPE_ACCEPT = 1
uint8 SEATADJUST_RESULT_TYPE_UNAVALIBLE =2
uint8 SEATADJUST_RESULT_TYPE_FAILED = 3
uint8 SEATADJUST_RESULT_TYPE_REJECT = 4
uint8 SEATADJUST_RESULT_TYPE_CANCEL = 5
---
# feedback definition
uint32 count