DB_URL = "/home/mi/black_box.db"
topic_names = ["touch_status"]

[[tables]]
name = "TouchStatus"
fields = [["timestamp", "INT", "NOT NULL"], ["touch_state", "INT", "NOT NULL"]]
key = "timestamp"

[[tables]]
name = "Test"
fields = [["id", "INT", "NOT NULL"],["content", "INT", "NOT NULL"]]
key = "id"
