# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "battery"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567

[[array]]
description = ""
can_package_num = 8
can_id = ["0x08842000", "0x08842001", "0x08842002", "0x08842003", "0x08842004", "0x08842005", "0x08842006", "0x08842007"]
array_name = "battery_status"

[[array]]
description = ""
can_package_num = 6
can_id = ["0x08852000", "0x08852001", "0x08852002", "0x08852003", "0x08852004", "0x08852005"]
array_name = "abnormal_status"

[[array]]
description = ""
can_package_num = 6
can_id = ["0x08862000", "0x08862001", "0x08862002", "0x08862003", "0x08862004", "0x08862005"]
array_name = "normal_status"

[[var]]
description = ""
can_id = "0x08840200"
var_name = "normal_mode"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08840400"
var_name = "charging"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08840800"
var_name = "finished_charging"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08850000"
var_name = "motor_power_down"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08850200"
var_name = "soft_shutdown"
var_type = "u8"
parser_param = [0, 0]

[[cmd]]
description = ""
cmd_name = "cmd_normal_mode"
can_id = "0x08880000"

[[cmd]]
description = ""
cmd_name = "cmd_turn_off_motor"
can_id = "0x08880200"

[[cmd]]
description = ""
cmd_name = "cmd_low_power_consumption"
can_id = "0x08880400"

[[cmd]]
description = ""
cmd_name = "cmd_soft_shutdown"
can_id = "0x08880800"

[[cmd]]
description = ""
cmd_name = "cmd_file_transfer"
can_id = "0x08890000"

[[cmd]]
description = ""
cmd_name = "cmd_ota_upgrade"
can_id = "0x08890200"

[[cmd]]
description = ""
cmd_name = "cmd_test"
can_id = "0x08890400"





