# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "battery"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567


[[array]]
description = ""
can_package_num = 2
can_id = ["0x00834100", "0x00834101"]
array_name = "battery_status"

[[array]]
description = ""
can_package_num = 1
can_id = ["0x00810200"]
array_name = "bms_enable_on_ack"

[[array]]
description = ""
can_package_num = 1
can_id = ["0x00810100"]
array_name = "bms_enable_off_ack"

[[cmd]]
description = ""
cmd_name = "bms_enable_on"
can_id = "0x00800200"

[[cmd]]
description = ""
cmd_name = "bms_enable_off"
can_id = "0x00800100"

[[cmd]]
description = ""
cmd_name = "cmd_normal_mode"
can_id = "0x00822100"

[[cmd]]
description = ""
cmd_name = "cmd_turn_off_motor"
can_id = "0x00822200"

[[cmd]]
description = ""
cmd_name = "cmd_turn_off_wireless_charging"
can_id = "0x00824000"

[[cmd]]
description = ""
cmd_name = "cmd_turn_on_wireless_charging"
can_id = "0x00824100"