# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "battery"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567



[[array]]
description = ""
can_package_num = 1
can_id = ["0x00822100"]
array_size = [8]
array_name = "battery_status"



[[array]]
description = ""
can_package_num = 1
can_id = ["0x00828100"]
array_size = [6]
array_name = "normal_status"


[[array]]
description = ""
can_package_num = 1
can_id = ["0x00828200"]
array_size = [6]
array_name = "abnormal_status"



[[var]]
description = ""
can_id = "0x08840200"
var_name = "normal_mode"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08840400"
var_name = "charging"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08840800"
var_name = "finished_charging"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08850000"
var_name = "motor_power_down"
var_type = "u8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x08850200"
var_name = "soft_shutdown"
var_type = "u8"
parser_param = [0, 0]

[[cmd]]
description = ""
cmd_name = "cmd_normal_mode"
can_id = "0x00830100"

[[cmd]]
description = ""
cmd_name = "cmd_turn_off_motor"
can_id = "0x00830200"

[[cmd]]
description = ""
cmd_name = "cmd_low_power_consumption"
can_id = "0x00830400"

[[cmd]]
description = ""
cmd_name = "cmd_soft_shutdown"
can_id = "0x00830800"

[[cmd]]
description = ""
cmd_name = "cmd_file_transfer"
can_id = "0x00834000"

[[cmd]]
description = ""
cmd_name = "cmd_ota_upgrade"
can_id = "0x00836000"

[[cmd]]
description = ""
cmd_name = "cmd_test"
can_id = "0x00838100"





