# head can toml 
protocol = "can"
name = "head_led"

can_interface = "can1"
extended_frame = true
canfd_enable = false
timeout_us = 1234567


[[cmd]]
description = "head enable on cmd"
cmd_name = "enable_on"
can_id = "0x04882A00"
ctrl_len = 0
ctrl_data = []


[[var]]
description = "head enable on ack"
can_id = "0x04892A00"
var_name = "enable_on_ack"
var_type = "i8"
parser_param = [0, 0]