# 该toml配置文件用于规定各模块使用灯的优先级。
# 为方便未加入优先级的模块进行调试，将undefined优先级最高。用户在调试时，可将
# "bridge/protocol/ros/srv/LedExecute.srv" request中client字段
# id越小优先级越高

[[priority]]
client = "lowpower"
id = 0

[[priority]]
client = "bms"
id = 1

[[priority]]
client = "connector"
id = 2

[[priority]]
client = "vp"
id = 3

[[priority]]
client = "tracking"
id = 4

[[priority]]
client = "system"
id = 5


