# -- embed params -- #
# protocol = "can"             (string)
# name = "can_device_name"     (string)
# [optional] for_send = false  (true / false)
protocol = "can"
name = "can_device_1"
for_send = true

# -- can params -- #
# can_interface = "can0"             (string)
# [optional] extended_frame = false  (true / false)
# [optional] canfd_enable = false    (true / false)
# [optional] timeout_us = 3'000'000  (int64)
can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1000000




##
#[[var]]
#can_id = "0x0301'00'00"
#var_name = "OFF"
#var_type = "u8"
#parser_param = [0,0]
#parser_type = "var"
#description = "this is example named OFF"


#[[var]]
#can_id = "0x0301'00'01"
#var_name = "ON"
#var_type = "u8"
#parser_param = [0, 7, 0]
#parser_type = "bit"
#description = "this is example named ON"

[[var]]
can_id = "0x0302'00'00"
var_name = "effect_id"
var_type = "u8"
parser_param = [0, 7, 0]
parser_type = "bit"
description = "this is example named BREATH"

#[[var]]
#can_id = "0x0301'00'03"
#var_name = "BLINK"
#var_type = "u8"
#parser_param = [0, 7, 0]
#parser_type = "bit"
#description = "this is example named BLINK"
