# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "tail_led"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567


[[cmd]]
description = ""
cmd_name = "enable_on"
can_id = "0x01030200"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "enable_off"
can_id = "0x01030400"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "PIC_1"
can_id = "0x01030600"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "PIC_2"
can_id = "0x01030700"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "PIC_ANIMATION"
can_id = "0x01030800"
ctrl_len = 1
ctrl_data = ["0x00"]