[controller]
actuators = ["motion_manager", "audio", "device_manager", "sensor_manager"， "RealSenseActuator"]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
default_time = 100 # milliseconds
default_state = "Uninitialized"

[actuator.motion_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.audio]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [240000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.device_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.sensor_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.RealSenseActuator]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]
