[controller]
actuators = ["audio", "device_manager", "sensor_manager", "motion_manager", "algorithm_manager", "vp_engine"]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
default_time = 100 # milliseconds
default_state = "Uninitialized"

[actuator.audio]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [240000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.device_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.sensor_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.motion_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.algorithm_manager]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [240000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

[actuator.vp_engine]
states = ["SetUp", "TearDown", "SelfCheck", "Active", "DeActive", "Protected", "LowPower", "OTA", "Error"]
times = [120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000, 120000]

