[dylidar]
frame_id = "laser_frame"
port = "/dev/ttyTHS0"
ignore_array = ""
baudrate = 512000
lidar_type = 0
device_type = 0
sample_rate = 10
abnormal_check_count = 4
resolution_fixed = false
reversion = true
inverted = false
auto_reconnect = true
isSingleChannel = false
intensity = true
support_motor_dtr = false
angle_max = 90.0
angle_min = -90.0
range_max = 30.0
range_min = 0.01
frequency = 10.0
invalid_range_is_inf = false
filter = true
