# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "tof_head"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567

#left
[[array]]
description = ""
can_package_num = 8
can_id = ["0x01854000", "0x01854001", "0x01854002", "0x01854003", "0x01854004", "0x01854005", "0x01854006", "0x01854007"]
array_name = "left_tof_data_array"


[[var]]
description = ""
can_id = "0x01854008"
var_name = "left_tof_data_clock"
var_type = "u64"
parser_param = [0, 7]

#right
[[array]]
description = ""
can_package_num = 8
can_id = ["0x01874000", "0x01874001", "0x01874002", "0x01874003", "0x01874004", "0x01874005", "0x01874006", "0x01874007"]
array_name = "right_tof_data_array"


[[var]]
description = ""
can_id = "0x01874008"
var_name = "right_tof_data_clock"
var_type = "u64"
parser_param = [0, 7]


[[var]]
description = ""
can_id = "0x018F2200"
var_name = "enable_on_ack"
var_type = "i8"
parser_param = [0, 0]

[[var]]
description = ""
can_id = "0x018F2400"
var_name = "enable_off_ack"
var_type = "i8"
parser_param = [0, 0]


[[cmd]]
description = ""
cmd_name = "enable_on"
can_id = "0x018E2200"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "enable_off"
can_id = "0x018E2400"
ctrl_len = 1
ctrl_data = ["0x00"]