# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "left_rear_tof"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567


#left_rear
[[array]]
description = ""
can_package_num = 17
can_id = ["0x020F4000", "0x020F4001", "0x020F4002", "0x020F4003", "0x020F4004", "0x020F4005", "0x020F4006", "0x020F4007", "0x020F4008", "0x020F4009", "0x020F400A", "0x020F400B", "0x020F400C", "0x020F400D", "0x020F400E", "0x020F400F", "0x020F4010"]
array_name = "data"

[[array]]
description = ""
can_package_num = 1
can_id = ["0x020F2200"]
array_name = "enable_on_ack"

[[array]]
description = ""
can_package_num = 1
can_id = ["0x020F2400"]
array_name = "enable_off_ack"

[[cmd]]
description = ""
cmd_name = "enable_on"
can_id = "0x020E2200"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "enable_off"
can_id = "0x020E2400"
ctrl_len = 1
ctrl_data = ["0x00"]