# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "ultrasonic"

can_interface = "can1"
extended_frame = true
canfd_enable = false
timeout_us = 1234567

[[array]]
description = ""
can_package_num = 1
can_id = ["0x01834000"]
array_name = "data"

[[array]]
description = ""
can_package_num = 1
can_id = ["0x01832200"]
array_name = "enable_on_ack"

[[array]]
description = ""
can_package_num = 1
can_id = ["0x01832400"]
array_name = "enable_off_ack"


[[cmd]]
description = ""
cmd_name = "enable_on"
can_id = "0x01822200"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "enable_off"
can_id = "0x01822400"
ctrl_len = 1
ctrl_data = ["0x00"]